name: Do Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: maven

      - name: Prepare release
        run: mvn --batch-mode test release:prepare

      - name: Perform release
        run: mvn --batch-mode test release:perform



